version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: jobboard-db
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: