spring.datasource.url=jdbc:postgresql://localhost:5435/jobboard
spring.datasource.username=jobboard
spring.datasource.password=jobboard

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=${JWT_SECRET:9IOYJtCqYKNp2v/cjeMxsgC/awz/UhDj6Zw1lMA4k76LkGmp37WCYKJO6wfWXorb}
