spring.application.name=jobBoard

spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=50
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Security 
jwt.secret=JdFxJW+oE8J6HQ/qSmC+CjzCMwp7KeKAOIbV69LiYJOB0EmLMvoMSXMgzYhBmn6r
jwt.expiration=86400000